CREATE WAREHOUSE test_wh_2 WAREHOUSE_SIZE=XSMALL INITIALLY_SUSPENDED=TRUE;

INSERT INTO DEMO.HELLO_WORLD (FIRST_NAME, LAST_NAME, AGE)
    VALUES ('x', 'y',25);

INSERT INTO DEMO.HELLO_WORLD (FIRST_NAME, LAST_NAME, AGE)
    VALUES ('3', '3',25);


INSERT INTO DEMO.HELLO_WORLD (FIRST_NAME, LAST_NAME, AGE)
    VALUES ('4', '4',25);
