INSERT INTO DEMO.HELLO_WORLD (FIRST_NAME, LAST_NAME, AGE)
    VALUES ('Sam', 'Singh',25);

INSERT INTO DEMO.HELLO_WORLD (FIRST_NAME, LAST_NAME, AGE)
    VALUES ('a', 'b',25);

use schema DEMO;
CREATE TABLE sample_table
(
   FIRST_NAME VARCHAR
  ,LAST_NAME VARCHAR
);